# Upptime Configuration for Hibas Monitoring
# Docs: https://upptime.js.org/docs/configuration

owner: Salberg87
repo: website-status

# =============================================================================
# SITES TO MONITOR
# =============================================================================
sites:
  - name: Hibas Test
    url: https://test.hibas.no
    maxResponseTime: 5000
    icon: https://test.hibas.no/favicon.ico

  - name: Hibas Preview
    url: https://preview.hibas.no
    maxResponseTime: 5000
    icon: https://preview.hibas.no/favicon.ico

  - name: Hafjell Hytter
    url: https://hafjellhytter.no
    maxResponseTime: 5000
    icon: https://hafjellhytter.no/favicon.ico

  # Uncomment after Jan 15 launch:
  # - name: Hibas
  #   url: https://hibas.no
  #   maxResponseTime: 5000
  #   icon: https://hibas.no/favicon.ico

# =============================================================================
# STATUS PAGE CONFIGURATION
# =============================================================================
status-website:
  baseUrl: /website-status
  logoUrl: https://test.hibas.no/favicon.ico
  name: Hibas Status
  introTitle: "**Hibas** er oppe og kjører"
  introMessage: Denne siden viser status for Hibas sine nettsider. Oppdateres automatisk hvert 5. minutt.
  navbar:
    - title: Status
      href: /
    - title: Hibas
      href: https://hibas.no
      target: _blank

# =============================================================================
# NOTIFICATIONS
# =============================================================================
# Email notifications
notifications:
  - type: email
    to: fredrik@pifre.no
  - type: email
    to: Hansi@hibas.no

# =============================================================================
# INCIDENT SETTINGS
# =============================================================================
workflowSchedule:
  uptime: "*/5 * * * *"      # Check every 5 minutes
  responseTime: "0 23 * * *"  # Response time summary daily at 23:00
  staticSite: "0 1 * * *"     # Rebuild status site daily at 01:00
  summary: "0 0 * * *"        # Daily summary at midnight

# Commit settings
commitMessages:
  statusChange: "$SITE_NAME is $STATUS ($RESPONSE_TIME ms)"
  commitAuthor:
    name: "Upptime Bot"
    email: "upptime@hibas.no"

# =============================================================================
# INTERNATIONALIZATION (Norwegian)
# =============================================================================
i18n:
  activeIncidents: Aktive hendelser
  allSystemsOperational: Alle systemer er operative
  incidentReport: "Hendelsesrapport for $DATE"
  incidentTitle: Detaljer
  incidentDetails: Hendelsesdetaljer
  noIncidents: Ingen hendelser rapportert.
  pageTitle: $SITE_NAME Status
  pastIncidents: Tidligere hendelser
  responseTime: Responstid
  uptime: Oppetid
  url: Nettadresse
  status: Status
  up: Oppe
  down: Nede
  degraded: Redusert ytelse
  ms: ms
  loading: Laster...
  navStatus: Status
  navGitHub: GitHub
